/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Me
 */
export interface Me {
    /**
     * 
     * @type {string}
     * @memberof Me
     */
    username?: string;
}

/**
 * Check if a given object implements the Me interface.
 */
export function instanceOfMe(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MeFromJSON(json: any): Me {
    return MeFromJSONTyped(json, false);
}

export function MeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Me {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
    };
}

export function MeToJSON(value?: Me | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
    };
}

