/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewOrder
 */
export interface NewOrder {
    /**
     * 
     * @type {string}
     * @memberof NewOrder
     */
    symbol?: string;
    /**
     * 
     * @type {number}
     * @memberof NewOrder
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof NewOrder
     */
    side?: NewOrderSideEnum;
}


/**
 * @export
 */
export const NewOrderSideEnum = {
    Buy: 'BUY',
    Sell: 'SELL'
} as const;
export type NewOrderSideEnum = typeof NewOrderSideEnum[keyof typeof NewOrderSideEnum];


/**
 * Check if a given object implements the NewOrder interface.
 */
export function instanceOfNewOrder(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NewOrderFromJSON(json: any): NewOrder {
    return NewOrderFromJSONTyped(json, false);
}

export function NewOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'symbol': !exists(json, 'symbol') ? undefined : json['symbol'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
        'side': !exists(json, 'side') ? undefined : json['side'],
    };
}

export function NewOrderToJSON(value?: NewOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'symbol': value.symbol,
        'quantity': value.quantity,
        'side': value.side,
    };
}

