name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  CI: true 

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with: 
          node-version: '18.x'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      
      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build libs and test-app
        run: yarn build

      - name: Unit tests
        run: yarn test

  contract-test-signalr:

    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with: 
          node-version: '18.x'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      
      - name: Install dotnet tools
        run: dotnet tool install --global TypedSignalR.Client.TypeScript.Generator
      
      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Generate typescript definition for signalr service
        run: yarn --cwd packages/signalr/signalr-test-client-api generate:api
      
      - name: Build packages
        run: yarn build:libs
        
      - name: Contact tests REMOTE
        run: |
          nohup dotnet run --urls=http://localhost:6002/ --project=packages/signalr/signalr-test-dotnet-svc &
          sleep 10 # enough time to startup?
          SIGNALR_REMOTE_PORT=6002 yarn --cwd packages/signalr/signalr-test-fake-svc test:contract

 